enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

pluginManagement {
    includeBuild("build-logic")
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // Generated by scripts/ci/build-spotiflac-backend.sh before Gradle runs.
        // Using Maven coordinates avoids AGP's unsupported direct-local-AAR
        // dependency path when :feature:downloads is bundled as an Android library.
        maven { url = uri(rootDir.resolve("vendor-maven")) }
    }
}

rootProject.name = "Harmony"

include(":app")
include(":core:common")
include(":core:model")
include(":domain:playback")
include(":playback:service")
include(":core:media")
include(":domain:library")
include(":core:database")
include(":data:library")
include(":core:dsp-native")
include(":domain:analysis")
include(":data:analysis")
include(":domain:similarity")
include(":data:similarity")
include(":domain:shuffle")
include(":core:datastore")
include(":core:ui")
include(":feature:library")
include(":feature:player")
include(":feature:playlists")
include(":feature:equalizer")
include(":feature:settings")
include(":feature:downloads")
include(":feature:discover")
include(":feature:home")
include(":sync:analysis-worker")
// Added in later phases:
// include(":core:database"), ":core:media", ":core:dsp-native", ":core:datastore",
// ":domain:library", ":domain:analysis", ":domain:similarity", ":domain:shuffle",
// ":data:*", ":feature:*", ":sync:analysis-worker"
