package com.harmony.feature.discover.provider

import com.harmony.feature.discover.model.AlbumGenre.*
import com.harmony.feature.discover.model.DiscoverAlbum

/** Public album facts and cover links verified on 2026-09-06. Listening notes are original Harmony copy. */
internal object ShflExtendedCatalog {
    val albums = listOf(
        DiscoverAlbum("Kind-of-Blue", "Kind of Blue", "Miles Davis", 1959,
            setOf(JAZZ), listOf("So What"),
            "Listen to how the soloists leave space for one another; the quieter passages are as memorable as the themes.",
            "https://images.theshfl.com/5981743408480256_600.jpg", 0xFFBFA88B),
        DiscoverAlbum("Time-Out", "Time Out", "The Dave Brubeck Quartet", 1959,
            setOf(JAZZ), listOf("Take Five"),
            "The familiar rhythm is an invitation to an album full of playful changes in time and touch.",
            "https://images.theshfl.com/5785696807682048_600.jpg", 0xFF9FBCBD, setOf("Dave Brubeck", "The Dave Brubeck Quartet", "Dave Brubeck Quartet")),
        DiscoverAlbum("A-Love-Supreme", "A Love Supreme", "John Coltrane", 1965,
            setOf(JAZZ), listOf("Acknowledgement"),
            "Let the four sections run together. Returning motifs turn individual solos into a sustained conversation.",
            "https://images.theshfl.com/5020726356606976_600.jpg", 0xFFCDA5AF),
        DiscoverAlbum("Head-Hunters", "Head Hunters", "Herbie Hancock", 1973,
            setOf(JAZZ, FUNK), listOf("Chameleon"),
            "Follow the bass beyond the opening groove: the band keeps finding fresh angles inside the rhythm.",
            "https://images.theshfl.com/4899815645249536_600.jpg", 0xFFA8B891),
        DiscoverAlbum("GetzGilberto", "Getz/Gilberto", "Stan Getz, João Gilberto", 1964,
            setOf(JAZZ, LATIN), listOf("The Girl from Ipanema"),
            "Stay for the balance between soft singing, guitar and saxophone, with each instrument making room for the others.",
            "https://images.theshfl.com/6043382455468032_600.jpg", 0xFFCCAC78, setOf("Stan Getz", "João Gilberto", "Stan Getz & João Gilberto", "Stan Getz, João Gilberto")),
        DiscoverAlbum("Mingus-Ah-Um", "Mingus Ah Um", "Charles Mingus", 1959,
            setOf(JAZZ), listOf("Goodbye Pork Pie Hat"),
            "Move between the fast ensemble passages and slower melodies to hear the full range of the band.",
            "https://images.theshfl.com/6536463533473792_600.jpg", 0xFFA69EC2),
        DiscoverAlbum("Master-of-Puppets", "Master of Puppets", "Metallica", 1986,
            setOf(METAL), listOf("Master of Puppets"),
            "Follow the long builds and acoustic contrasts that give the heaviest riffs their force.",
            "https://images.theshfl.com/4842755528327168_600.jpg", 0xFFBFA88B),
        DiscoverAlbum("Paranoid", "Paranoid", "Black Sabbath", 1970,
            setOf(METAL, ROCK), listOf("Paranoid"),
            "The slower tracks and sudden changes in pace reveal more than the famous opening riffs.",
            "https://images.theshfl.com/4910750187388928_600.jpg", 0xFF9FBCBD),
        DiscoverAlbum("Reign-in-Blood", "Reign in Blood", "Slayer", 1986,
            setOf(METAL), listOf("Raining Blood"),
            "A short, intense sequence whose tightly connected riffs reward a start-to-finish listen.",
            "https://images.theshfl.com/5618654750179328_600.jpg", 0xFFCDA5AF),
        DiscoverAlbum("Powerslave", "Powerslave", "Iron Maiden", 1984,
            setOf(METAL), listOf("2 Minutes to Midnight"),
            "Stay for the longer arrangements and the way the guitars trade melodies around the vocals.",
            "https://images.theshfl.com/4939606139076608_600.jpg", 0xFFA8B891),
        DiscoverAlbum("Rust-in-Peace", "Rust in Peace", "Megadeth", 1990,
            setOf(METAL), listOf("Holy Wars... The Punishment Due"),
            "Listen for the rhythmic precision under the guitar solos; the whole band keeps the momentum moving.",
            "https://images.theshfl.com/4756418485813248_600.jpg", 0xFFCCAC78),
        DiscoverAlbum("Rage-Against-the-Machine", "Rage Against the Machine", "Rage Against the Machine", 1992,
            setOf(METAL, ROCK), listOf("Killing in the Name"),
            "The bass and drums are worth following on their own before returning to the voice and guitar.",
            "https://images.theshfl.com/4795626181099520_600.jpg", 0xFFA69EC2),
        DiscoverAlbum("Blue", "Blue", "Joni Mitchell", 1971,
            setOf(FOLK), listOf("A Case of You"),
            "Stay with the smaller, quieter songs: their details change how the familiar melodies feel.",
            "https://images.theshfl.com/5156416922845184_600.jpg", 0xFFBFA88B),
        DiscoverAlbum("Pink-Moon", "Pink Moon", "Nick Drake", 1972,
            setOf(FOLK), listOf("Pink Moon"),
            "A brief record for an uninterrupted listen, with little between you, the voice and the guitar.",
            "https://images.theshfl.com/5723096048730112_600.jpg", 0xFF9FBCBD),
        DiscoverAlbum("Harvest", "Harvest", "Neil Young", 1972,
            setOf(FOLK, COUNTRY), listOf("Heart of Gold"),
            "The softer songs and rougher edges make the familiar single part of a wider, more reflective record.",
            "https://images.theshfl.com/5964606782570496_600.jpg", 0xFFCDA5AF),
        DiscoverAlbum("Bridge-Over-Troubled-Water", "Bridge Over Troubled Water", "Simon & Garfunkel", 1970,
            setOf(FOLK, POP), listOf("The Boxer"),
            "Let the harmonies and shifts in arrangement carry you through the quieter tracks between the hits.",
            "https://images.theshfl.com/5593187984867328_600.jpg", 0xFFA8B891),
        DiscoverAlbum("Five-Leaves-Left", "Five Leaves Left", "Nick Drake", 1969,
            setOf(FOLK), listOf("River Man"),
            "Listen for the strings and small guitar details that give these restrained songs their depth.",
            "https://images.theshfl.com/4641269284339712_600.jpg", 0xFFCCAC78),
        DiscoverAlbum("Carrie--Lowell", "Carrie & Lowell", "Sufjan Stevens", 2015,
            setOf(FOLK, INDIE), listOf("Should Have Known Better"),
            "Give the quiet spaces time. Repeated images and gentle changes of texture tie the songs together.",
            "https://images.theshfl.com/5093007099428864_600.jpg", 0xFFA69EC2),
        DiscoverAlbum("At-Folsom-Prison", "At Folsom Prison", "Johnny Cash", 1968,
            setOf(COUNTRY), listOf("Folsom Prison Blues"),
            "The room and audience become part of the music; keep the sequence intact to hear that exchange.",
            "https://images.theshfl.com/6362590372429824_600.jpg", 0xFFBFA88B),
        DiscoverAlbum("Jolene", "Jolene", "Dolly Parton", 1974,
            setOf(COUNTRY), listOf("Jolene"),
            "The recognizable title song opens an album of direct storytelling and carefully shaped vocal performances.",
            "https://images.theshfl.com/5658935982292992_600.jpg", 0xFF9FBCBD),
        DiscoverAlbum("Red-Headed-Stranger", "Red Headed Stranger", "Willie Nelson", 1975,
            setOf(COUNTRY), listOf("Blue Eyes Crying in the Rain"),
            "Follow the songs in order: the spare arrangements leave room for a story to unfold.",
            "https://images.theshfl.com/6194169471041536_600.jpg", 0xFFCDA5AF),
        DiscoverAlbum("Coat-of-Many-Colors", "Coat of Many Colors", "Dolly Parton", 1971,
            setOf(COUNTRY), listOf("Coat of Many Colors"),
            "Listen for the storytelling in the less familiar tracks as much as the melodies you already know.",
            "https://images.theshfl.com/5192424284487680_600.jpg", 0xFFA8B891),
        DiscoverAlbum("The-Gilded-Palace-of-Sin", "The Gilded Palace of Sin", "The Flying Burrito Brothers", 1969,
            setOf(COUNTRY, ROCK), listOf("Sin City"),
            "The harmonies connect country phrasing with the feel of a rock band, especially between the singles.",
            "https://images.theshfl.com/6348730471022592_600.jpg", 0xFFCCAC78),
        DiscoverAlbum("Grievous-Angel", "Grievous Angel", "Gram Parsons", 1974,
            setOf(COUNTRY), listOf("Love Hurts"),
            "Stay for the vocal exchanges and the way tenderness and roughness sit together in the performances.",
            "https://images.theshfl.com/5281241624477696_600.jpg", 0xFFA69EC2),
        DiscoverAlbum("Born-Under-a-Bad-Sign", "Born Under a Bad Sign", "Albert King", 1967,
            setOf(BLUES), listOf("Born Under a Bad Sign"),
            "Listen for the small changes in guitar phrasing against a rhythm section that keeps everything grounded.",
            "https://images.theshfl.com/6265096720351232_600.jpg", 0xFFBFA88B),
        DiscoverAlbum("Texas-Flood", "Texas Flood", "Stevie Ray Vaughan and Double Trouble", 1983,
            setOf(BLUES, ROCK), listOf("Pride and Joy"),
            "The quieter guitar passages give the fast runs context; follow the band's pacing across the record.",
            "https://images.theshfl.com/5538467102588928_600.jpg", 0xFF9FBCBD, setOf("Stevie Ray Vaughan & Double Trouble", "Stevie Ray Vaughan", "Stevie Ray Vaughan and Double Trouble")),
        DiscoverAlbum("Live-at-the-Regal", "Live at the Regal", "B.B. King", 1965,
            setOf(BLUES), listOf("Every Day I Have the Blues"),
            "An audience and a band answering each other: listen for the pauses as well as the guitar lines.",
            "https://images.theshfl.com/5988891240693760_600.jpg", 0xFFCDA5AF, liveRecording = true),
        DiscoverAlbum("At-Last", "At Last!", "Etta James", 1960,
            setOf(BLUES, SOUL_POP), listOf("At Last"),
            "The title song is only one side of the voice. Stay for the changes in energy and phrasing.",
            "https://images.theshfl.com/5502628637179904_600.jpg", 0xFFA8B891),
        DiscoverAlbum("Moanin-in-the-Moonlight", "Moanin' in the Moonlight", "Howlin' Wolf", 1959,
            setOf(BLUES), listOf("Smokestack Lightnin'"),
            "A voice, a riff and a rhythm section can do a lot; follow the tiny variations between songs.",
            "https://images.theshfl.com/6568838728515584_600.jpg", 0xFFCCAC78),
        DiscoverAlbum("Exodus-1", "Exodus", "Bob Marley & The Wailers", 1977,
            setOf(REGGAE), listOf("Three Little Birds"),
            "Let the reflective opening stretch lead into the brighter, more familiar songs later in the sequence.",
            "https://images.theshfl.com/6676498123587584_600.jpg", 0xFFA69EC2, setOf("Bob Marley", "Bob Marley & The Wailers", "Bob Marley and the Wailers")),
        DiscoverAlbum("Catch-a-Fire", "Catch a Fire", "The Wailers", 1973,
            setOf(REGGAE), listOf("Stir It Up"),
            "Listen for the vocal harmonies and the space around the bass; the album keeps a remarkably steady pull.",
            "https://images.theshfl.com/Catch-a-Fire_600.jpg", 0xFFBFA88B, setOf("Bob Marley", "Bob Marley & The Wailers", "Bob Marley and the Wailers", "The Wailers")),
        DiscoverAlbum("Two-Sevens-Clash", "Two Sevens Clash", "Culture", 1977,
            setOf(REGGAE), listOf("Two Sevens Clash"),
            "The ensemble vocals reward a longer listen, with small melodic turns riding a steady rhythmic foundation.",
            "https://images.theshfl.com/6634912236961792_600.jpg", 0xFF9FBCBD),
        DiscoverAlbum("Funky-Kingston", "Funky Kingston", "Toots & The Maytals", 1973,
            setOf(REGGAE), listOf("Funky Kingston"),
            "Keep an ear on the organ and bass beneath the voice; the groove changes shape without losing its warmth.",
            "https://images.theshfl.com/5722597228544000_600.jpg", 0xFFCDA5AF, setOf("Toots & The Maytals", "Toots and the Maytals")),
        DiscoverAlbum("Heart-of-the-Congos", "Heart of the Congos", "The Congos", 1977,
            setOf(REGGAE), listOf("Fisherman"),
            "Stay for the vocal blend and the deep, spacious production that makes each song feel connected.",
            "https://images.theshfl.com/6308282859782144_600.jpg", 0xFFA8B891),
        DiscoverAlbum("Zombie", "Zombie", "Fela Kuti", 1976,
            setOf(AFRICAN, FUNK), listOf("Zombie"),
            "Let the long patterns develop. The exchanges between horns, percussion and voice build gradually.",
            "https://images.theshfl.com/5154836194525184_600.jpg", 0xFFCCAC78, setOf("Fela Kuti", "Fela Kuti and Afrika 70", "Fela Kuti & Africa 70")),
        DiscoverAlbum("Expensive-Shit", "Expensive Shit", "Fela Kuti", 1975,
            setOf(AFRICAN, FUNK), listOf("Water No Get Enemy"),
            "Give the rhythms time to settle before following the different instruments moving through them.",
            "https://images.theshfl.com/6296573193486336_600.jpg", 0xFFA69EC2, setOf("Fela Kuti", "Fela Kuti & Africa 70", "Fela Kuti and Africa 70")),
        DiscoverAlbum("Graceland", "Graceland", "Paul Simon", 1986,
            setOf(WORLD, POP), listOf("You Can Call Me Al"),
            "The familiar choruses sit among intricate bass lines, vocal exchanges and rhythmic surprises.",
            "https://images.theshfl.com/5450398374559744_600.jpg", 0xFFBFA88B),
        DiscoverAlbum("Savane", "Savane", "Ali Farka Touré", 2006,
            setOf(AFRICAN, BLUES), listOf("Savane"),
            "Listen to the repeating guitar phrases and the voices that move around them; small changes carry the songs.",
            "https://images.theshfl.com/5630702733230080_600.jpg", 0xFF9FBCBD),
        DiscoverAlbum("Talking-Timbuktu", "Talking Timbuktu", "Ali Farka Touré, Ry Cooder", 1994,
            setOf(AFRICAN, BLUES), listOf("Diaraby"),
            "The two guitars leave each other space, finding connections through phrasing and rhythm.",
            "https://images.theshfl.com/5762025120595968_600.jpg", 0xFFCDA5AF, setOf("Ali Farka Touré", "Ali Farka Touré & Ry Cooder", "Ry Cooder")),
        DiscoverAlbum("Music-in-Exile", "Music in Exile", "Songhoy Blues", 2015,
            setOf(AFRICAN, BLUES), listOf("Soubour"),
            "Stay for the band's interplay: guitar hooks, bass and drums keep answering the vocals.",
            "https://images.theshfl.com/4656899366584320_600.jpg", 0xFFA8B891),
        DiscoverAlbum("Buena-Vista-Social-Club", "Buena Vista Social Club", "Buena Vista Social Club", 1997,
            setOf(LATIN, WORLD), listOf("Chan Chan"),
            "The slower songs are as inviting as the familiar opener. Listen for the exchanges between the singers and instruments.",
            "https://images.theshfl.com/4769637736644608_600.jpg", 0xFFCCAC78),
        DiscoverAlbum("Acabou-Chorare", "Acabou Chorare", "Novos Baianos", 1972,
            setOf(LATIN), listOf("Preta Pretinha"),
            "Let the guitar rhythms and ensemble vocals lead you through the record's many changes in mood.",
            "https://images.theshfl.com/5182876375056384_600.jpg", 0xFFA69EC2, setOf("Os Novos Baianos", "Novos Baianos")),
        DiscoverAlbum("Chega-de-Saudade", "Chega de Saudade", "João Gilberto", 1959,
            setOf(LATIN, JAZZ), listOf("Chega de Saudade"),
            "The quiet guitar and understated voice invite close listening, especially between the familiar melodies.",
            "https://images.theshfl.com/6279168119537664_v1_600.jpg", 0xFFBFA88B),
        DiscoverAlbum("Transa", "Transa", "Caetano Veloso", 1972,
            setOf(LATIN), listOf("You Don't Know Me"),
            "Follow the movement between languages and the rhythmic conversations that hold the performances together.",
            "https://images.theshfl.com/5673590162718720_600.jpg", 0xFF9FBCBD),
        DiscoverAlbum("Wave-1", "Wave", "Antônio Carlos Jobim", 1967,
            setOf(LATIN, JAZZ), listOf("Wave"),
            "The arrangements frame the melodies with space and color; the quieter pieces deserve the same attention as the title track.",
            "https://images.theshfl.com/5965978181566464_600.jpg", 0xFFCDA5AF),
        DiscoverAlbum("The-Rise-and-Fall-of-Ziggy-Stardust-and-the-Spiders-from-Mars", "The Rise and Fall of Ziggy Stardust and the Spiders from Mars", "David Bowie", 1972,
            setOf(ROCK, POP), listOf("Starman"),
            "Let the songs arrive in sequence, with quieter moments setting up the bigger theatrical turns.",
            "https://images.theshfl.com/6000960165904384_600.jpg", 0xFFA8B891),
        DiscoverAlbum("Hunky-Dory", "Hunky Dory", "David Bowie", 1971,
            setOf(ROCK, POP), listOf("Life on Mars?"),
            "The piano details and changes of character make the less familiar songs as rewarding as the hits.",
            "https://images.theshfl.com/5692223823806464_600.jpg", 0xFFCCAC78),
        DiscoverAlbum("Pet-Sounds", "Pet Sounds", "The Beach Boys", 1966,
            setOf(POP), listOf("Wouldn't It Be Nice"),
            "The vocal layers and unexpected instrumental colors open up when the songs are heard together.",
            "https://images.theshfl.com/5583676310028288_600.jpg", 0xFFA69EC2),
        DiscoverAlbum("Abbey-Road", "Abbey Road", "The Beatles", 1969,
            setOf(ROCK, POP), listOf("Come Together"),
            "Stay for the second half, where short fragments and returning ideas become part of a longer flow.",
            "https://images.theshfl.com/6294823304691712_600.jpg", 0xFFBFA88B),
        DiscoverAlbum("Confessions-on-a-Dance-Floor", "Confessions on a Dance Floor", "Madonna", 2005,
            setOf(POP, ELECTRONIC), listOf("Hung Up"),
            "Keep the tracks in order: the transitions make the changing dance rhythms feel like one long evening.",
            "https://images.theshfl.com/5694331843248128_600.jpg", 0xFF9FBCBD),
        DiscoverAlbum("Body-Talk", "Body Talk", "Robyn", 2010,
            setOf(POP, ELECTRONIC), listOf("Dancing on My Own"),
            "The big choruses are only part of the appeal; follow the tension between bright rhythms and vulnerable vocals.",
            "https://images.theshfl.com/5650654647287808_v1_600.jpg", 0xFFCDA5AF),
        DiscoverAlbum("Play", "Play", "Moby", 1999,
            setOf(ELECTRONIC), listOf("Porcelain"),
            "Follow the changes between sampled voices, soft instrumentals and bigger beats across the full sequence.",
            "https://images.theshfl.com/Play_v2_600.jpg", 0xFFA8B891),
        DiscoverAlbum("The-Fat-of-the-Land", "The Fat of the Land", "The Prodigy", 1997,
            setOf(ELECTRONIC), listOf("Firestarter"),
            "The quieter stretches set up the impact of the big beats; listen to how the album manages its energy.",
            "https://images.theshfl.com/5765005228113920_600.jpg", 0xFFCCAC78),
        DiscoverAlbum("Moon-Safari", "Moon Safari", "Air", 1998,
            setOf(ELECTRONIC), listOf("All I Need"),
            "Small keyboard and bass details reward headphones, especially in the spaces around the familiar melodies.",
            "https://images.theshfl.com/6514271663947776_600.jpg", 0xFFA69EC2),
        DiscoverAlbum("Since-I-Left-You", "Since I Left You", "The Avalanches", 2000,
            setOf(ELECTRONIC), listOf("Frontier Psychiatrist"),
            "Let the samples and transitions lead the way; the pleasure comes from hearing one idea open into another.",
            "https://images.theshfl.com/6032789564555264_600.jpg", 0xFFBFA88B),
        DiscoverAlbum("Homework", "Homework", "Daft Punk", 1997,
            setOf(ELECTRONIC), listOf("Around the World"),
            "The repeated patterns keep changing in small ways. Stay with a track long enough to hear the movement inside it.",
            "https://images.theshfl.com/6309329959387136_600.jpg", 0xFF9FBCBD),
        DiscoverAlbum("Selected-Ambient-Works-8592", "Selected Ambient Works 85-92", "Aphex Twin", 1992,
            setOf(ELECTRONIC, AMBIENT), listOf("Xtal"),
            "The melodies emerge gradually from the rhythms and textures; give the quieter tracks a little space.",
            "https://images.theshfl.com/4541222517473280_600.jpg", 0xFFCDA5AF),
        DiscoverAlbum("Madvillainy", "Madvillainy", "Madvillain", 2004,
            setOf(HIP_HOP), listOf("All Caps"),
            "Short tracks, abrupt turns and dense wordplay make this a record to follow closely from start to finish.",
            "https://images.theshfl.com/6460914790301696_600.jpg", 0xFFA8B891, setOf("Madvillain", "MF DOOM", "Madlib")),
        DiscoverAlbum("good-kid-mAAd-city", "good kid, m.A.A.d city", "Kendrick Lamar", 2012,
            setOf(HIP_HOP), listOf("Money Trees"),
            "Keep the sequence intact to follow the characters, scenes and recurring ideas around the familiar songs.",
            "https://images.theshfl.com/6540850439913472_600.jpg", 0xFFCCAC78),
        DiscoverAlbum("Stankonia", "Stankonia", "OutKast", 2000,
            setOf(HIP_HOP), listOf("Ms. Jackson"),
            "The two voices pull in different directions while the arrangements keep finding surprising places to meet.",
            "https://images.theshfl.com/6200699096399872_600.jpg", 0xFFA69EC2),
        DiscoverAlbum("Whats-Going-On", "What's Going On", "Marvin Gaye", 1971,
            setOf(SOUL_POP), listOf("What's Going On"),
            "The transitions and returning musical ideas make the familiar songs feel like parts of one conversation.",
            "https://images.theshfl.com/6107731039617024_v1_600.jpg", 0xFFBFA88B),
        DiscoverAlbum("Super-Fly-Original-Soundtrack", "Superfly", "Curtis Mayfield", 1972,
            setOf(SOUL_POP, FUNK), listOf("Superfly"),
            "Listen to the bass, strings and voice together; the quieter passages carry as much tension as the recognizable themes.",
            "https://images.theshfl.com/4792505174327296_600.jpg", 0xFF9FBCBD),
        DiscoverAlbum("Hot-Buttered-Soul", "Hot Buttered Soul", "Isaac Hayes", 1969,
            setOf(SOUL_POP), listOf("Walk On By"),
            "The long arrangements leave room for the voice and instruments to take their time with each melody.",
            "https://images.theshfl.com/5263306109485056_600.jpg", 0xFFCDA5AF),
        DiscoverAlbum("Voodoo", "Voodoo", "D'Angelo", 2000,
            setOf(RNB, SOUL_POP), listOf("Untitled (How Does It Feel)"),
            "Listen for the slight rhythmic shifts between bass, drums and vocals; the grooves reveal their detail gradually.",
            "https://images.theshfl.com/5282465648214016_600.jpg", 0xFFA8B891),
        DiscoverAlbum("Mamas-Gun", "Mama's Gun", "Erykah Badu", 2000,
            setOf(RNB, SOUL_POP), listOf("Bag Lady"),
            "Stay for the slower songs and instrumental exchanges that give the familiar hooks a richer setting.",
            "https://images.theshfl.com/5133320333557760_600.jpg", 0xFFCCAC78),
        DiscoverAlbum("SwitchedOn-Bach", "Switched-On Bach", "Wendy Carlos", 1968,
            setOf(CLASSICAL, ELECTRONIC), listOf("Brandenburg Concerto No. 3 in G Major"),
            "Follow familiar musical shapes through unusual electronic colors, with each line easy to hear on its own.",
            "https://images.theshfl.com/5379803330904064_v1_600.jpg", 0xFFA69EC2),
        DiscoverAlbum("Music-for-18-Musicians", "Music for 18 Musicians", "Steve Reich", 1978,
            setOf(CLASSICAL, AMBIENT), listOf("Pulses"),
            "Let the pulse carry you across gradual changes; the interest is in the movement between repeating patterns.",
            "https://images.theshfl.com/6049821190258688_600.jpg", 0xFFBFA88B),
        DiscoverAlbum("Ambient-1-Music-for-Airports", "Ambient 1: Music for Airports", "Brian Eno", 1978,
            setOf(AMBIENT), listOf("1/1"),
            "Give the repeating phrases time to drift apart and reconnect. This is music that changes your sense of pace.",
            "https://images.theshfl.com/Ambient-1--Music-for-Airports_v4_600.jpg", 0xFF9FBCBD),
        DiscoverAlbum("Heaven-or-Las-Vegas", "Heaven or Las Vegas", "Cocteau Twins", 1990,
            setOf(INDIE, POP), listOf("Heaven or Las Vegas"),
            "The voice and guitars blend into changing colors; the less familiar tracks deepen the album's atmosphere.",
            "https://images.theshfl.com/6337038697627648_600.jpg", 0xFFCDA5AF),
        DiscoverAlbum("Loveless", "Loveless", "My Bloody Valentine", 1991,
            setOf(INDIE, ROCK), listOf("Only Shallow"),
            "Listen beyond the wall of guitar for melodies that appear and disappear inside the texture.",
            "https://images.theshfl.com/5285937969889280_600.jpg", 0xFFA8B891),
        DiscoverAlbum("The-Queen-Is-Dead", "The Queen Is Dead", "The Smiths", 1986,
            setOf(INDIE, ROCK), listOf("There Is a Light That Never Goes Out"),
            "The sharp guitar lines and changes of mood give the familiar choruses their place in a larger record.",
            "https://images.theshfl.com/4733988031692800_600.jpg", 0xFFCCAC78),
        DiscoverAlbum("Nevermind", "Nevermind", "Nirvana", 1991,
            setOf(ROCK, INDIE), listOf("Come As You Are"),
            "Stay for the contrast between quieter verses, heavy choruses and the songs that pull back from both.",
            "https://images.theshfl.com/6544013213564928_600.jpg", 0xFFA69EC2),
    )
}
